#!/usr/bin/env bash
#
# Copyright (C) 2026 SpacemiT (Hangzhou) Technology Co. Ltd.
# SPDX-License-Identifier: Apache-2.0
#

set -euo pipefail

# Run cpplint on tracked C/C++ source files (team-enforced).
#
# Usage:
#   bash scripts/lint/cpplint.sh              # lint all tracked C/C++ files
#   bash scripts/lint/cpplint.sh <path>       # lint tracked C/C++ files under <path>
#   bash scripts/lint/cpplint.sh <file.cpp>   # lint a single tracked file
#
# Optional env:
#   CPPLINT_ARGS="--verbose=0" bash scripts/lint/cpplint.sh

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "${ROOT_DIR}"

if ! command -v cpplint >/dev/null 2>&1; then
  echo "[cpplint] ERROR: cpplint not found."
  echo "[cpplint] Install: python3 -m pip install --user cpplint"
  echo "[cpplint] (On Ubuntu with PEP 668, prefer: pipx install cpplint)"
  exit 127
fi

CONFIG_FILE="${CPPLINT_CONFIG:-scripts/lint/.cpplintrc}"
CONFIG_ARGS=()
HEADER_GUARD_STYLE="${CPPLINT_HEADER_GUARD_STYLE:-default}"
if [[ -f "${CONFIG_FILE}" ]]; then
  # Parse a minimal subset of cpplint cfg settings and convert to CLI flags.
  # Supported keys:
  #   linelength=120     -> --linelength=120
  #   extensions=cpp,hpp -> --extensions=cpp,hpp
  #   filter=-x,+y       -> --filter=-x,+y
  while IFS= read -r line || [[ -n "${line}" ]]; do
    # Trim leading/trailing whitespace
    line="${line#"${line%%[![:space:]]*}"}"
    line="${line%"${line##*[![:space:]]}"}"
    [[ -z "${line}" ]] && continue
    [[ "${line}" == \#* ]] && continue
    [[ "${line}" == "set noparent" ]] && continue

    case "${line}" in
      linelength=*) CONFIG_ARGS+=(--linelength="${line#linelength=}") ;;
      extensions=*) CONFIG_ARGS+=(--extensions="${line#extensions=}") ;;
      filter=*) CONFIG_ARGS+=(--filter="${line#filter=}") ;;
      headerguard=*) HEADER_GUARD_STYLE="${line#headerguard=}" ;;
    esac
  done < "${CONFIG_FILE}"
else
  echo "[cpplint] WARN: config file not found: ${CONFIG_FILE} (using cpplint defaults)"
fi

filter_cpp_files() {
  # Reads NUL-delimited paths from stdin and outputs NUL-delimited paths of C/C++ files.
  while IFS= read -r -d '' f; do
    case "${f}" in
      output/*|target/*|components/thirdparty/*) continue ;;
    esac
    is_generated_cpp "${f}" && continue
    case "${f}" in
      *.c|*.cc|*.cpp|*.cxx|*.h|*.hpp|*.hh|*.hxx) printf '%s\0' "${f}" ;;
    esac
  done
}

is_generated_cpp() {
  local f="$1"
  [[ -f "${f}" ]] || return 1
  head -n 80 "${f}" | grep -q "generated by the tool fastddsgen"
}

expected_header_guard_no_trailing_underscore() {
  # path/to/test_framework.h -> TEST_FRAMEWORK_H
  local f="$1"
  local base name ext macro
  base="$(basename "${f}")"
  name="${base%.*}"
  ext="${base##*.}"
  macro="${name}_${ext}"
  printf '%s' "${macro}" | tr '[:lower:]' '[:upper:]' | sed -E 's/[^A-Z0-9]+/_/g'
}

extract_guard_macro() {
  # Args: <file> <directive>
  # directive: ifndef|define
  # Output: "<line_number>:<macro>" or empty
  local f="$1"
  local directive="$2"
  local pattern
  # Match object-like macro only (exclude function-like e.g. FOO(...))
  pattern="^[[:space:]]*#${directive}[[:space:]]+[A-Za-z_][A-Za-z0-9_]*([[:space:]]|$)"
  local hit
  hit="$(grep -nE "${pattern}" "${f}" | head -n1 || true)"
  [[ -z "${hit}" ]] && return 0
  local line_num line_txt macro
  line_num="${hit%%:*}"
  line_txt="${hit#*:}"
  macro="$(printf '%s' "${line_txt}" | sed -E "s/^[[:space:]]*#${directive}[[:space:]]+([A-Za-z_][A-Za-z0-9_]*).*/\\1/")"
  printf '%s:%s\n' "${line_num}" "${macro}"
}

check_header_guards_basename_no_trailing_underscore() {
  local -a files=("$@")
  local had=0
  local f expected ifndef_hit define_hit ifndef_line ifndef_macro define_line define_macro

  for f in "${files[@]}"; do
    case "${f}" in
      *.h|*.hpp|*.hh|*.hxx) ;;
      *) continue ;;
    esac

    expected="$(expected_header_guard_no_trailing_underscore "${f}")"
    ifndef_hit="$(extract_guard_macro "${f}" "ifndef")"
    define_hit="$(extract_guard_macro "${f}" "define")"

    if [[ -z "${ifndef_hit}" || -z "${define_hit}" ]]; then
      echo "${f}:1: missing header guard (#ifndef/#define). Expected: ${expected}"
      had=1
      continue
    fi

    ifndef_line="${ifndef_hit%%:*}"
    ifndef_macro="${ifndef_hit#*:}"
    define_line="${define_hit%%:*}"
    define_macro="${define_hit#*:}"

    if [[ "${ifndef_macro}" != "${expected}" ]]; then
      echo "${f}:${ifndef_line}: header guard macro should be ${expected} (got ${ifndef_macro})"
      had=1
    fi
    if [[ "${define_macro}" != "${expected}" ]]; then
      echo "${f}:${define_line}: header guard macro should be ${expected} (got ${define_macro})"
      had=1
    fi
    if [[ "${ifndef_macro}" != "${define_macro}" ]]; then
      echo "${f}:${define_line}: #ifndef macro (${ifndef_macro}) does not match #define macro (${define_macro})"
      had=1
    fi
  done

  return "${had}"
}

check_indentation_4_spaces() {
  local -a files=("$@")
  local had=0
  local f
  local line_no
  local line
  local trimmed
  local leading
  local spaces
  local in_block_comment

  for f in "${files[@]}"; do
    line_no=0
    in_block_comment=0
    while IFS= read -r line || [[ -n "${line}" ]]; do
      ((line_no += 1))

      trimmed="${line#"${line%%[![:space:]]*}"}"

      # Skip comment-only lines.
      if (( in_block_comment == 1 )); then
        [[ "${trimmed}" == *"*/"* ]] && in_block_comment=0
        continue
      fi
      [[ "${trimmed}" == //* ]] && continue
      if [[ "${trimmed}" == '/*'* ]]; then
        [[ "${trimmed}" != *"*/"* ]] && in_block_comment=1
        continue
      fi
      [[ "${trimmed}" == \** ]] && continue

      # Skip blank lines.
      [[ "${line}" =~ ^[[:space:]]*$ ]] && continue
      # Skip preprocessor directives; they are typically column-sensitive.
      [[ "${line}" =~ ^[[:space:]]*# ]] && continue

      leading="${line%%[![:space:]]*}"
      [[ -z "${leading}" ]] && continue

      # Indentation must use spaces only.
      if [[ "${leading}" == *$'\t'* ]]; then
        echo "${f}:${line_no}: indentation must use spaces only (tab found)"
        had=1
        continue
      fi

      spaces=${#leading}
      if (( spaces % 4 != 0 )); then
        echo "${f}:${line_no}: indentation must be a multiple of 4 spaces (got ${spaces})"
        had=1
      fi
    done < "${f}"
  done

  return "${had}"
}

is_git_repo() {
  git rev-parse --is-inside-work-tree >/dev/null 2>&1
}

list_cpp_files_find() {
  # Args: <path or empty>
  # Output: NUL-delimited list of files
  local base="${1:-.}"

  if [[ -f "${base}" ]]; then
    # Single file
    case "${base}" in
      output/*|target/*|components/thirdparty/*) return 0 ;;
      *.c|*.cc|*.cpp|*.cxx|*.h|*.hpp|*.hh|*.hxx)
        is_generated_cpp "${base}" || printf '%s\0' "${base}"
        ;;
    esac
    return 0
  fi

  # Directory (or ".")
  find "${base}" -type f \
    \( -name '*.c' -o -name '*.cc' -o -name '*.cpp' -o -name '*.cxx' -o -name '*.h' -o -name '*.hpp' -o -name '*.hh' -o -name '*.hxx' \) \
    -not -path '*/output/*' \
    -not -path '*/target/*' \
    -not -path '*/components/thirdparty/*' \
    -not -path '*/build/*' \
    -not -path '*/install/*' \
    -not -path '*/log/*' \
    -print0 | while IFS= read -r -d '' f; do
      is_generated_cpp "${f}" || printf '%s\0' "${f}"
    done
}

TARGET_PATH="${1:-}"
if [[ -z "${TARGET_PATH}" ]]; then
  if is_git_repo; then
    # Lint all tracked files (filtered by extension + excluded dirs).
    mapfile -d '' FILES < <(git ls-files -z | filter_cpp_files)
  else
    # Fallback for tarball/zip source drops without .git directory.
    mapfile -d '' FILES < <(list_cpp_files_find ".")
  fi
else
  # Accept absolute or relative paths. Convert absolute to repo-relative if possible.
  if [[ "${TARGET_PATH}" = /* ]]; then
    if command -v realpath >/dev/null 2>&1; then
      ABS_TARGET="$(realpath -m "${TARGET_PATH}")"
      ABS_ROOT="$(realpath -m "${ROOT_DIR}")"
      case "${ABS_TARGET}" in
        "${ABS_ROOT}"/*) TARGET_PATH="${ABS_TARGET#"${ABS_ROOT}"/}" ;;
      esac
    fi
  fi

  if [[ -e "${TARGET_PATH}" ]]; then
    if is_git_repo; then
      # Lint tracked files under this path (or the file itself if it is a file).
      mapfile -d '' FILES < <(git ls-files -z -- "${TARGET_PATH}" | filter_cpp_files)
      # If the user explicitly pointed to a path but it's not tracked yet,
      # fall back to scanning the filesystem under that path.
      if [[ ${#FILES[@]} -eq 0 ]]; then
        mapfile -d '' FILES < <(list_cpp_files_find "${TARGET_PATH}")
      fi
    else
      # Fallback for non-git environments: lint files on disk under the given path.
      mapfile -d '' FILES < <(list_cpp_files_find "${TARGET_PATH}")
    fi
  else
    echo "[cpplint] ERROR: path not found: ${TARGET_PATH}"
    exit 2
  fi
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
  if [[ -z "${TARGET_PATH}" ]]; then
    echo "[cpplint] No matching tracked C/C++ files found."
  else
    echo "[cpplint] No matching tracked C/C++ files found under: ${TARGET_PATH}"
  fi
  exit 0
fi

if [[ -z "${TARGET_PATH}" ]]; then
  echo "[cpplint] Linting ${#FILES[@]} files..."
else
  echo "[cpplint] Linting ${#FILES[@]} files under: ${TARGET_PATH}"
fi

# cpplint returns non-zero when issues are found (desired for CI).
# Always pass --repository=. so header-guard derivation is stable even outside a git checkout.
had_error=0
BASE_ARGS=(--repository="." "${CONFIG_ARGS[@]}")

if ! check_indentation_4_spaces "${FILES[@]}"; then
  echo "[cpplint] indentation check failed (rule=4 spaces)."
  had_error=1
fi

if [[ "${HEADER_GUARD_STYLE}" == "basename_no_trailing_underscore" ]]; then
  if ! check_header_guards_basename_no_trailing_underscore "${FILES[@]}"; then
    echo "[cpplint] headerguard check failed (style=${HEADER_GUARD_STYLE})."
    had_error=1
  fi
  # Run cpplint for all other checks. build/header_guard should be disabled via filter.
  # shellcheck disable=SC2086
  cpplint "${BASE_ARGS[@]}" ${CPPLINT_ARGS:-} "${FILES[@]}" || had_error=1
elif [[ "${HEADER_GUARD_STYLE}" == "basename" ]]; then
  # Force header-guard derivation to only use the file basename by setting --root
  # to the directory that contains the header.
  for f in "${FILES[@]}"; do
    case "${f}" in
      *.h|*.hpp|*.hh|*.hxx)
        root_dir="$(dirname "${f}")"
        # shellcheck disable=SC2086
        cpplint "${BASE_ARGS[@]}" --root="${root_dir}" ${CPPLINT_ARGS:-} "${f}" || had_error=1
        ;;
      *)
        # shellcheck disable=SC2086
        cpplint "${BASE_ARGS[@]}" ${CPPLINT_ARGS:-} "${f}" || had_error=1
        ;;
    esac
  done
else
  # shellcheck disable=SC2086
  cpplint "${BASE_ARGS[@]}" ${CPPLINT_ARGS:-} "${FILES[@]}" || had_error=1
fi

exit "${had_error}"


